# Generated by Django 5.2.8 on 2026-04-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='Costprice',
            field=models.FloatField(default='10'),
        ),
        migrations.AddField(
            model_name='product',
            name='Salesprice',
            field=models.FloatField(default='10'),
        ),
    ]
