# Generated by Django 5.2.8 on 2026-04-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_price_product_costprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Costprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Salesprice',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
